<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Product>Argotic Syndication Framework</Product>
    <Description>Argotic Entity Extensibility Class Library, that contains the classes, interfaces, and enumerations that enable web content syndication extensibility.</Description>
    <PackageDescription>20+ syndication extensions including iTunes, Dublin Core, Yahoo Media, Creative Commons, Trackback, Pingback, and more for extending RSS and Atom feeds.</PackageDescription>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Argotic.Common\Argotic.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\README.md" Pack="true" PackagePath="" />
  </ItemGroup>

</Project>
