<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>14.0</LangVersion>
        <Authors>Brian William Kuhn, endjin</Authors>
    </PropertyGroup>

    <PropertyGroup>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageDescription></PackageDescription>
        <PackageTags></PackageTags>
        <PackageReleaseNotes></PackageReleaseNotes>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Argotic.Common\Argotic.Common.csproj" />
        <ProjectReference Include="..\Argotic.Core\Argotic.Core.csproj" />
        <ProjectReference Include="..\Argotic.Extensions\Argotic.Extensions.csproj" />
    </ItemGroup>

    <PropertyGroup>
        <EnableNETAnalyzers>true</EnableNETAnalyzers>
        <AnalysisMode>AllEnabledByDefault</AnalysisMode>
        <AnalysisLevel>latest</AnalysisLevel>
    </PropertyGroup>

</Project>