<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Argotic.Examples</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console" Version="0.54.0" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.53.1" />
    <PackageReference Include="Spectre.IO" Version="0.21.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Argotic.Common\Argotic.Common.csproj" />
    <ProjectReference Include="..\Argotic.Core\Argotic.Core.csproj" />
    <ProjectReference Include="..\Argotic.Extensions\Argotic.Extensions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="SampleData\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
